<?php

namespace App\Http\Controllers\SoftEmp\Panel\Core\AccessControl;

use App\Http\Controllers\SoftEmp\Panel\CrudController;
use App\Models\Core\AccessControl\Occupation;
use App\Models\Core\AccessControl\Role;
use Illuminate\Http\Request;

/**
 * Class OccupationController
 * @package App\Http\Controllers\SoftEmp\Panel\Base\AccessControl
 */
class OccupationController extends CrudController
{
    private $role;

    /**
     * OccupationController constructor.
     * @param Occupation $occupation
     * @param Role $role
     */
    public function __construct(Occupation $occupation, Request $request, Role $role)
    {
        $pathView = 'softemp.panel.core.access_control.occupation';
        $groupRoute = 'panel.access.control.occupation';

        $this->role = $role;

        parent::__construct($occupation, $request, $groupRoute, $pathView);
    }

    public function store()
    {
        $role = $this->role->whereSlug('employee')->firstOrFail();
        $this->request['role_id'] = $role->id;
        return parent::store(); // TODO: Change the autogenerated stub
    }

}
