<?php

namespace App\Http\Controllers\SoftEmp\WebSite;

use App\Models\WebSite\About;
use Illuminate\Http\Request;

class AboutController extends CrudController
{
    private $pathImg = 'storage/softemp/panel/uploads/sobre/';

    protected $pathView = 'softemp.website.about';
    protected $groupRoute = 'softemp.website.about';

    public function __construct(About $model, Request $request)
    {
        parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    public function index()
    {

       //$about = $this->model->personLegals->find(env('EMPRESA_SOFTWARE_ID'));
        //$about = $this->model->wherePersonLegalId(env('EMPRESA_SOFTWARE_ID'))->first();
        $this->arrayData['about'] = $this->model->firstOrFail();
//         dd($this->arrayData['about']);
         $pathImg = $this->pathImg;

        $this->arrayData['opt'] = $this->optMeta->optimize('Sobre nos','Provedor de Internet, planos de internet fibra optica, a melhor internet de Garopaba e Imbituba', env('APP_URL').'/sobre','');

        return parent::index(); // TODO: Change the autogenerated stub
        //return view("{$this->pathView}.index",compact('about','pathImg'));
    }
}
