<?php

namespace App\Http\Controllers\SoftEmp\WebSite;

use App\Models\Core\People\Physical;
use Illuminate\Http\Request;

class HelpController extends CrudController
{
    protected $pathView = 'softemp.website.help';
    protected $groupRoute = 'softemp.website.help';

    public function __construct(Physical $model, Request $request)
    {
        parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->arrayData['opt'] = $this->optMeta->optimize('Suporte Gbit','Provedor de Internet, planos de internet fibra optica, a melhor internet de Garopaba e Imbituba', env('APP_URL').'/ajuda','');
        return parent::index(); // TODO: Change the autogenerated stub
        //return view("{$this->pathView}.index");
    }
}
