<?php

namespace App\Http\Controllers\SoftEmp\WebSite;

use App\Http\Controllers\SoftEmp\WebSite\CrudController;
use App\Models\Core\People\Physical;
use Illuminate\Http\Request;

class PlansController extends CrudController
{
    protected $pathView = 'softemp.website.plans';
    protected $groupRoute = 'softemp.website.plans';

    public function __construct(Physical $model, Request $request)
    {
        parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->arrayData['opt'] = $this->optMeta->optimize('Planos de Internet','Provedor de Internet, planos de internet fibra optica, a melhor internet de Garopaba e Imbituba', env('APP_URL').'/planos','');

        return parent::index(); // TODO: Change the autogenerated stub
    }
}
