<?php

namespace App\Http\Controllers\SoftEmp\Panel\Core\Address;

use App\Http\Controllers\SoftEmp\Panel\CrudController;
use App\Http\Validators\Address\CityValidator;
use App\Http\Validators\Address\NeighboarhoodValidator;
use App\Models\Core\Address\City;
use App\Models\Core\Address\Neighboarhood;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Models\Core\Address\State;

class NeighboarhoodController extends CrudController
{

    /**
     * path file views
     *
     * @var type
     */
    protected $pathView = 'softemp.panel.address.neighboarhood';
    protected $groupRoute = 'panel.address.neighboarhood';
    private $city;

    /**
     * NeighboarhoodsController constructor.
     * @param Neighboarhood $model
     * @param Request $request
     * @param NeighboarhoodValidator $validator
     * @param City $city
     */
    public function __construct(Neighboarhood $model, Request $request, City $city)
    {
//        $this->validator = $validator;
        $this->city = $city;

        parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    public function getNeighboarhood()
    {
        if ($this->request->has('city') && $this->request->has('neighboarhood')) {
            $city_id = $this->request->city;
            $search = $this->request->neighboarhood;
            $data = $this->model->select("id", "name")
                ->whereCityId($city_id)
                ->where('name', 'LIKE', "%$search%")
                ->get();

            if (count($data)) {
                return response()->json($data, 200);
            }
        }
        $data = [
            0=>[
                'id'=>'new',
                'name'=>'Bairro não encontrado'
            ],
        ];
        return response()->json($data,200);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //verifica se existe a permission
        if (Gate::denies('address.city-view')) {
            return redirect()->back()->with('error', trans('grud.msg_permission_denied'));
        }

        return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //verifica se existe a permission
        if (Gate::denies('city-create')) {
            return redirect()->back()->with('error', trans('grud.msg_permission_denied'));
        }
        //pegando as Cidades
        $cities = $this->city->all();

        return view("{$this->nameView}.create", compact('cities'));
    }

    public function store()
    {
        return parent::store(); // TODO: Change the autogenerated stub
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->find($id);
        $cities = $this->city->all();

        return view("{$this->nameView}.edit", compact('data', 'cities'));
    }
}
