<?php

namespace App\Http\Controllers\SoftEmp\Panel\Core\Address;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\SoftEmp\CrudController;
use App\Models\Core\Address\State;
use App\Models\Core\Address\Countrie;
use App\Http\Validators\Address\StateValidator;

class StatesController extends CrudController {

    /**
     * path file views
     *
     * @var type
     */
    protected $nameView = 'softemp.panel.address.states';

    /**
     * route basic
     *
     * @var type
     */
    protected $route = 'panel.address.states';
    protected $countrie;

    /**
     * StatesController constructor.
     * @param State $model
     * @param Request $request
     * @param StateValidator $validator
     * @param Countrie $countrie
     */
    public function __construct(State $model, Request $request, StateValidator $validator, Countrie $countrie) {
        $this->model = $model;
        $this->request = $request;
        $this->validator = $validator;
        $this->countrie = $countrie;
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getState(){
        $data = [];
        if($this->request->has('countrie')&&$this->request->has('state')){
            $countrie_id = $this->request->countrie;
            $search = $this->request->state;
            $data = $this->model->select("id","name","initials")
                ->whereCountrieId($countrie_id)
                ->where('name','LIKE',"%$search%")
                ->get();
        }
        return response()->json($data);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //verifica se existe a permission
        if (Gate::denies('address.state-view')) {
            return redirect()->back()->with('error', trans('grud.msg_permission_denied'));
        }

        return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //verifica se existe a permission
        if (Gate::denies('state-create')) {
            return redirect()->back()->with('error', trans('grud.msg_permission_denied'));
        }
        //pegando os países
        $countries = $this->countrie->all();

        return view("{$this->nameView}.create", compact('countries'));
    }

    public function store()
    {
        return parent::store(); // TODO: Change the autogenerated stub
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->find($id);
        $countries = $this->countrie->all();

        return view("{$this->nameView}.edit", compact('data','countries'));
    }
}
