<?php
use App\Models\Core\Address\Continent;
use App\Models\Core\Address\Countrie;
use App\Models\Core\Address\State;
use App\Models\Core\Address\City;
use App\Models\Core\Address\Neighboarhood;
use App\Models\Core\Address\Street;
use App\Models\Core\Address\AddressType;
/**
 * Created by PhpStorm.
 * User: paulo
 * Date: 04/03/18
 * Time: 15:42
 */
/**
 * Cadastrando os Continentes
 */
$continents_an = Continent::create(['id'=>1, 'name' => 'Antarctica', 'initials' => 'AN']);
$continents_af = Continent::create(['id'=>2, 'name' => 'Africa', 'initials' => 'AF']);
$continents_as = Continent::create(['id'=>3, 'name' => 'Asia', 'initials' => 'AS']);
$continents_eu = Continent::create(['id'=>4, 'name' => 'Europe', 'initials' => 'EU']);
$continents_na = Continent::create(['id'=>5, 'name' => 'North America', 'initials' => 'NA']);
$continents_sa = Continent::create(['id'=>6, 'name' => 'South America', 'initials' => 'SA']);
$continents_oc = Continent::create(['id'=>7, 'name' => 'Oceania', 'initials' => 'OC']);
/**
 * Cadastrando os Países
 */
$countrie_af = Countrie::create(['id'=>1, 'name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'ddi' => '93']);
$countrie_ax = Countrie::create(['id'=>2, 'name' => 'Åland Islands', 'iso2' => 'AX', 'iso3' => 'ALA', 'ddi' => '358 18']);
$countrie_al = Countrie::create(['id'=>3, 'name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'ddi' => '355']);
$countrie_dz = Countrie::create(['id'=>4, 'name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'ddi' => '213']);
$countrie_as = Countrie::create(['id'=>5, 'name' => 'American Samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'ddi' => '1 684']);
$countrie_ad = Countrie::create(['id'=>6, 'name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'ddi' => '376']);
$countrie_ao = Countrie::create(['id'=>7, 'name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'ddi' => '244']);
$countrie_ai = Countrie::create(['id'=>8, 'name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'ddi' => '1 264']);
$countrie_aq = Countrie::create(['id'=>9, 'name' => 'Antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'ddi' => '6721']);
$countrie_ag = Countrie::create(['id'=>10, 'name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'ddi' => '1 268']);
$countrie_ar = Countrie::create(['id'=>11, 'name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ATR', 'ddi' => '54']);
$countrie_am = Countrie::create(['id'=>12, 'name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'ddi' => '374']);
$countrie_aw = Countrie::create(['id'=>13, 'name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'ddi' => '297']);
$countrie_au = Countrie::create(['id'=>14, 'name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'ddi' => '61']);
$countrie_at = Countrie::create(['id'=>15, 'name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'ddi' => '43']);
$countrie_az = Countrie::create(['id'=>16, 'name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'ddi' => '994']);
$countrie_bs = Countrie::create(['id'=>17, 'name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'ddi' => '1 242']);
$countrie_bh = Countrie::create(['id'=>18, 'name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'ddi' => '973']);
$countrie_bd = Countrie::create(['id'=>19, 'name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'ddi' => '880']);
$countrie_bb = Countrie::create(['id'=>20, 'name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'ddi' => '1 246']);
$countrie_by = Countrie::create(['id'=>21, 'name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'ddi' => '375']);
$countrie_be = Countrie::create(['id'=>22, 'name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BLE', 'ddi' => '32']);
$countrie_bz = Countrie::create(['id'=>23, 'name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'ddi' => '501']);
$countrie_bj = Countrie::create(['id'=>24, 'name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'ddi' => '229']);
$countrie_bm = Countrie::create(['id'=>25, 'name' => 'Bermuda', 'iso2' => 'BM', 'iso3' => 'BMU', 'ddi' => '1 441']);
$countrie_bt = Countrie::create(['id'=>26, 'name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'ddi' => '975']);
$countrie_bo = Countrie::create(['id'=>27, 'name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'ddi' => '591']);
$countrie_bq = Countrie::create(['id'=>28, 'name' => 'Bonaire, Sint Eustatius and Saba', 'iso2' => 'BQ', 'iso3' => 'BES', 'ddi' => '5997']);
$countrie_ba = Countrie::create(['id'=>29, 'name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'ddi' => '387']);
$countrie_bw = Countrie::create(['id'=>30, 'name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'ddi' => '267']);
$countrie_bv = Countrie::create(['id'=>31, 'name' => 'Bouvet Island', 'iso2' => 'BV', 'iso3' => 'BVT', 'ddi' => '47']);
$countrie_br = Countrie::create(['id'=>32, 'name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'ddi' => '55']);
$countrie_io = Countrie::create(['id'=>33, 'name' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'ddi' => '246']);
$countrie_bn = Countrie::create(['id'=>34, 'name' => 'Brunei Darussalam', 'iso2' => 'BN', 'iso3' => 'BRN', 'ddi' => '673']);
$countrie_bg = Countrie::create(['id'=>35, 'name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'ddi' => '359']);
$countrie_bf = Countrie::create(['id'=>36, 'name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'ddi' => '226']);
$countrie_bi = Countrie::create(['id'=>37, 'name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'ddi' => '257']);
$countrie_kh = Countrie::create(['id'=>38, 'name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'ddi' => '855']);
$countrie_cm = Countrie::create(['id'=>39, 'name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'ddi' => '237']);
$countrie_ca = Countrie::create(['id'=>40, 'name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'ddi' => '1']);
$countrie_cv = Countrie::create(['id'=>41, 'name' => 'Cape Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'ddi' => '238']);
$countrie_ky = Countrie::create(['id'=>42, 'name' => 'Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'ddi' => '1 345']);
$countrie_cf = Countrie::create(['id'=>43, 'name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'ddi' => '236']);
$countrie_td = Countrie::create(['id'=>44, 'name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'ddi' => '235']);
$countrie_cl = Countrie::create(['id'=>45, 'name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'ddi' => '56']);
$countrie_cn = Countrie::create(['id'=>46, 'name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'ddi' => '86']);
$countrie_cx = Countrie::create(['id'=>47, 'name' => 'Christmas Island', 'iso2' => 'CX', 'iso3' => 'CXR', 'ddi' => '61']);
$countrie_cc = Countrie::create(['id'=>48, 'name' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'ddi' => '61']);
$countrie_co = Countrie::create(['id'=>49, 'name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'ddi' => '57']);
$countrie_km = Countrie::create(['name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'ddi' => '269']);
$countrie_cd = Countrie::create(['name' => 'Congo, the Democratic Republic of the', 'iso2' => 'CD', 'iso3' => 'COD', 'ddi' => '242']);
$countrie_cg = Countrie::create(['name' => 'Congo', 'iso2' => 'CG', 'iso3' => 'CGO', 'ddi' => '243']);
$countrie_ck = Countrie::create(['name' => 'Cook Islands, the Democratic Republic of the', 'iso2' => 'CK', 'iso3' => 'COK', 'ddi' => '682']);
$countrie_cr = Countrie::create(['name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'ddi' => '506']);
$countrie_ci = Countrie::create(['name' => "Côte d'Ivoire", 'iso2' => 'CI', 'iso3' => 'CIV', 'ddi' => '225']);
$countrie_hr = Countrie::create(['name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'ddi' => '385']);
$countrie_cu = Countrie::create(['name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'ddi' => '53']);
$countrie_cw = Countrie::create(['name' => 'Curaçao', 'iso2' => 'CW', 'iso3' => 'CUW', 'ddi' => '599']);
$countrie_cy = Countrie::create(['name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'ddi' => '357']);
$countrie_cz = Countrie::create(['name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'ddi' => '420']);
$countrie_dk = Countrie::create(['name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'ddi' => '45']);
$countrie_dj = Countrie::create(['name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'ddi' => '253']);
$countrie_dm = Countrie::create(['name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'ddi' => '1 767']);
$countrie_do = Countrie::create(['name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'ddi' => '1 809/829/ 849']);
$countrie_ec = Countrie::create(['name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'ddi' => '593']);
$countrie_eg = Countrie::create(['name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'ddi' => '20']);
$countrie_sv = Countrie::create(['name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'ddi' => '503']);
$countrie_gq = Countrie::create(['name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'ddi' => '240']);
$countrie_er = Countrie::create(['name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'ddi' => '291']);
$countrie_ee = Countrie::create(['name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'ddi' => '372']);
$countrie_et = Countrie::create(['name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'ddi' => '251']);
$countrie_fk = Countrie::create(['name' => 'Falkland Islands (Malvinas)', 'iso2' => 'FK', 'iso3' => 'FLK', 'ddi' => '500']);
$countrie_fo = Countrie::create(['name' => 'Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'ddi' => '298']);
$countrie_fj = Countrie::create(['name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'ddi' => '679']);
$countrie_fi = Countrie::create(['name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'ddi' => '358']);
$countrie_fr = Countrie::create(['name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'ddi' => '33']);
$countrie_gf = Countrie::create(['name' => 'French Guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'ddi' => '594']);
$countrie_pf = Countrie::create(['name' => 'French Polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'ddi' => '689']);
$countrie_tf = Countrie::create(['name' => 'French Southern Territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'ddi' => '']);
$countrie_ga = Countrie::create(['name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'ddi' => '241']);
$countrie_gm = Countrie::create(['name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'ddi' => '220']);
$countrie_ge = Countrie::create(['name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'ddi' => '995']);
$countrie_de = Countrie::create(['name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'ddi' => '49']);
$countrie_gh = Countrie::create(['name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'ddi' => '233']);
$countrie_gi = Countrie::create(['name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'ddi' => '350']);
$countrie_gr = Countrie::create(['name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'ddi' => '30']);
$countrie_gl = Countrie::create(['name' => 'Greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'ddi' => '299']);
$countrie_gd = Countrie::create(['name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'ddi' => '1 473']);
$countrie_gp = Countrie::create(['name' => 'Guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'ddi' => '590']);
$countrie_gu = Countrie::create(['name' => 'Guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'ddi' => '1 671']);
$countrie_gt = Countrie::create(['name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'ddi' => '502']);
$countrie_gg = Countrie::create(['name' => 'Guernsey', 'iso2' => 'GG', 'iso3' => 'GGY', 'ddi' => '44']);
$countrie_gw = Countrie::create(['name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'ddi' => '245']);
$countrie_gn = Countrie::create(['name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'ddi' => '224']);
$countrie_gy = Countrie::create(['name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'ddi' => '592']);
$countrie_ht = Countrie::create(['name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'THI', 'ddi' => '509']);
$countrie_hm = Countrie::create(['name' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'iso3' => 'HMD', 'ddi' => '1 672']);
$countrie_va = Countrie::create(['name' => 'Holy See (Vatican City State)', 'iso2' => 'VA', 'iso3' => 'VAT', 'ddi' => '379']);
$countrie_hn = Countrie::create(['name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'ddi' => '504']);
$countrie_hk = Countrie::create(['name' => 'Hong Kong', 'iso2' => 'HK', 'iso3' => 'HKG', 'ddi' => '852']);
$countrie_hu = Countrie::create(['name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'ddi' => '36']);
$countrie_is = Countrie::create(['name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'ddi' => '354']);
$countrie_in = Countrie::create(['name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'ddi' => '91']);
$countrie_id = Countrie::create(['name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'ddi' => '62']);
$countrie_ir = Countrie::create(['name' => 'Iran, Islamic Republic of', 'iso2' => 'IR', 'iso3' => 'IRN', 'ddi' => '98']);
$countrie_iq = Countrie::create(['name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'ddi' => '964']);
$countrie_ie = Countrie::create(['name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IrL', 'ddi' => '353']);
$countrie_im = Countrie::create(['name' => 'Isle of Man', 'iso2' => 'IM', 'iso3' => 'IMN', 'ddi' => '44']);
$countrie_il = Countrie::create(['name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'ddi' => '972']);
$countrie_it = Countrie::create(['name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'ddi' => '39']);
$countrie_jm = Countrie::create(['name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'ddi' => '1 876']);
$countrie_jp = Countrie::create(['name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'ddi' => '81']);
$countrie_je = Countrie::create(['name' => 'Jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'ddi' => '44']);
$countrie_jo = Countrie::create(['name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'ddi' => '962']);
$countrie_kz = Countrie::create(['name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'ddi' => '7']);
$countrie_ke = Countrie::create(['name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'ddi' => '254']);
$countrie_ki = Countrie::create(['name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'ddi' => '686']);
$countrie_kp = Countrie::create(['name' => 'Korea, Democratic People\'s Republic of', 'iso2' => 'KP', 'iso3' => 'PRK', 'ddi' => '850']);
$countrie_kr = Countrie::create(['name' => 'Korea, Republic of', 'iso2' => 'KR', 'iso3' => 'KOR', 'ddi' => '82']);
$countrie_kw = Countrie::create(['name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'ddi' => '965']);
$countrie_kg = Countrie::create(['name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'ddi' => '996']);
$countrie_la = Countrie::create(['name' => 'Lao People\'s Democratic Republic', 'iso2' => 'LA', 'iso3' => 'LAO', 'ddi' => '856']);
$countrie_lv = Countrie::create(['name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'ddi' => '371']);
$countrie_lb = Countrie::create(['name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'ddi' => '961']);
$countrie_ls = Countrie::create(['name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'ddi' => '266']);
$countrie_lr = Countrie::create(['name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'ddi' => '231']);
$countrie_ly = Countrie::create(['name' => 'Libyan Arab Jamahiriya', 'iso2' => 'LY', 'iso3' => 'LBY', 'ddi' => '218']);
$countrie_li = Countrie::create(['name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'ddi' => '423']);
$countrie_lt = Countrie::create(['name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'ddi' => '370']);
$countrie_lu = Countrie::create(['name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'ddi' => '352']);
$countrie_mo = Countrie::create(['name' => 'Macao', 'iso2' => 'MO', 'iso3' => 'MAC', 'ddi' => '853']);
$countrie_mk = Countrie::create(['name' => 'Macedonia, the Former Yugoslav Republic of', 'iso2' => 'MK', 'iso3' => 'MKD', 'ddi' => '389']);
$countrie_mg = Countrie::create(['name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'ddi' => '261']);
$countrie_mw = Countrie::create(['name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'ddi' => '265']);
$countrie_my = Countrie::create(['name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'ddi' => '60']);
$countrie_mv = Countrie::create(['name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'ddi' => '960']);
$countrie_ml = Countrie::create(['name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'ddi' => '223']);
$countrie_mt = Countrie::create(['name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'ddi' => '356']);
$countrie_mh = Countrie::create(['name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'ddi' => '692']);
$countrie_mq = Countrie::create(['name' => 'Martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'ddi' => '596']);
$countrie_mr = Countrie::create(['name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'ddi' => '222']);
$countrie_mu = Countrie::create(['name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'ddi' => '230']);
$countrie_yt = Countrie::create(['name' => 'Mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'ddi' => '262']);
$countrie_mx = Countrie::create(['name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'ddi' => '52']);
$countrie_fm = Countrie::create(['name' => 'Micronesia, Federated States of', 'iso2' => 'FM', 'iso3' => 'FSM', 'ddi' => '691']);
$countrie_md = Countrie::create(['name' => 'Moldova, Republic of', 'iso2' => 'MD', 'iso3' => 'MDA', 'ddi' => '373']);
$countrie_mc = Countrie::create(['name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'ddi' => '377']);
$countrie_mn = Countrie::create(['name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'ddi' => '976']);
$countrie_me = Countrie::create(['name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'ddi' => '382']);
$countrie_ms = Countrie::create(['name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'ddi' => '1 664']);
$countrie_ma = Countrie::create(['name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'ddi' => '212']);
$countrie_mz = Countrie::create(['name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'ddi' => '258']);
$countrie_mm = Countrie::create(['name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'ddi' => '95']);
$countrie_na = Countrie::create(['name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'ddi' => '264']);
$countrie_nr = Countrie::create(['name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'ddi' => '674']);
$countrie_np = Countrie::create(['name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'ddi' => '977']);
$countrie_nl = Countrie::create(['name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'ddi' => '31']);
$countrie_nc = Countrie::create(['name' => 'New Caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'ddi' => '687']);
$countrie_nz = Countrie::create(['name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'ddi' => '64']);
$countrie_ni = Countrie::create(['name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'ddi' => '505']);
$countrie_ng = Countrie::create(['name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'ddi' => '234']);
$countrie_ne = Countrie::create(['name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'ddi' => '227']);
$countrie_nu = Countrie::create(['name' => 'Niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'ddi' => '683']);
$countrie_nf = Countrie::create(['name' => 'Norfolk Island', 'iso2' => 'NF', 'iso3' => 'NFK', 'ddi' => '6723']);
$countrie_mp = Countrie::create(['name' => 'Northern Mariana Islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'ddi' => '1 670']);
$countrie_no = Countrie::create(['name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'ddi' => '47']);
$countrie_om = Countrie::create(['name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'ddi' => '968']);
$countrie_pk = Countrie::create(['name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'ddi' => '92']);
$countrie_pw = Countrie::create(['name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'ddi' => '680']);
$countrie_ps = Countrie::create(['name' => 'Palestinian Territory, Occupied', 'iso2' => 'PS', 'iso3' => 'PSE', 'ddi' => '970']);
$countrie_pa = Countrie::create(['name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'ddi' => '507']);
$countrie_pg = Countrie::create(['name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'ddi' => '675']);
$countrie_py = Countrie::create(['name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'ddi' => '595']);
$countrie_pe = Countrie::create(['name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'ddi' => '51']);
$countrie_ph = Countrie::create(['name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'ddi' => '63']);
$countrie_pn = Countrie::create(['name' => 'Pitcairn', 'iso2' => 'PN', 'iso3' => 'PCN', 'ddi' => '64']);
$countrie_pl = Countrie::create(['name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'ddi' => '48']);
$countrie_pt = Countrie::create(['name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'ddi' => '351']);
$countrie_pr = Countrie::create(['name' => 'Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'ddi' => '1 787/939']);
$countrie_qa = Countrie::create(['name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'ddi' => '974']);
$countrie_re = Countrie::create(['name' => 'Réunion', 'iso2' => 'RE', 'iso3' => 'REU', 'ddi' => '262']);
$countrie_ro = Countrie::create(['name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'ddi' => '40']);
$countrie_ru = Countrie::create(['name' => 'Russian Federation', 'iso2' => 'RU', 'iso3' => 'RUS', 'ddi' => '7']);
$countrie_rw = Countrie::create(['name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'ddi' => '250']);
$countrie_bl = Countrie::create(['name' => 'Saint Barthélemy', 'iso2' => 'BL', 'iso3' => 'BLM', 'ddi' => '590']);
$countrie_sh = Countrie::create(['name' => 'Saint Helena', 'iso2' => 'SH', 'iso3' => 'SHN', 'ddi' => '290']);
$countrie_kn = Countrie::create(['name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'ddi' => '1 869']);
$countrie_lc = Countrie::create(['name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'ddi' => '1 758']);
$countrie_mf = Countrie::create(['name' => 'Saint Martin (French part)', 'iso2' => 'MF', 'iso3' => 'MAF', 'ddi' => '590']);
$countrie_pm = Countrie::create(['name' => 'Saint Pierre and Miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'ddi' => '508']);
$countrie_vc = Countrie::create(['name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'ddi' => '1 784']);
$countrie_ws = Countrie::create(['name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'ddi' => '685']);
$countrie_sm = Countrie::create(['name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'ddi' => '378']);
$countrie_st = Countrie::create(['name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'ddi' => '239']);
$countrie_sa = Countrie::create(['name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'ddi' => '966']);
$countrie_sn = Countrie::create(['name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'ddi' => '221']);
$countrie_rs = Countrie::create(['name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'ddi' => '381']);
$countrie_sc = Countrie::create(['name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'ddi' => '248']);
$countrie_sl = Countrie::create(['name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'ddi' => '232']);
$countrie_sg = Countrie::create(['name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'ddi' => '65']);
$countrie_sx = Countrie::create(['name' => 'Sint Maarten (Dutch part)', 'iso2' => 'SX', 'iso3' => 'SXM', 'ddi' => '1 721']);
$countrie_sk = Countrie::create(['name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'ddi' => '421']);
$countrie_si = Countrie::create(['name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'ddi' => '386']);
$countrie_sb = Countrie::create(['name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'ddi' => '677']);
$countrie_so = Countrie::create(['name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'ddi' => '252']);
$countrie_za = Countrie::create(['name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'ddi' => '27']);
$countrie_gs = Countrie::create(['name' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'iso3' => 'SGS', 'ddi' => '500']);
$countrie_ss = Countrie::create(['name' => 'South Sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'ddi' => '211']);
$countrie_es = Countrie::create(['name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'ddi' => '35']);
$countrie_lk = Countrie::create(['name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'ddi' => '94']);
$countrie_sd = Countrie::create(['name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'ddi' => '249']);
$countrie_sr = Countrie::create(['name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'ddi' => '597']);
$countrie_sj = Countrie::create(['name' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'iso3' => 'SJM', 'ddi' => '47']);
$countrie_sz = Countrie::create(['name' => 'Swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'ddi' => '268']);
$countrie_se = Countrie::create(['name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'ddi' => '46']);
$countrie_ch = Countrie::create(['name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'ddi' => '41']);
$countrie_sy = Countrie::create(['name' => 'Syrian Arab Republic', 'iso2' => 'SY', 'iso3' => 'SYR', 'ddi' => '963']);
$countrie_tw = Countrie::create(['name' => 'Taiwan, Province of China', 'iso2' => 'TW', 'iso3' => 'TWN', 'ddi' => '886']);
$countrie_tj = Countrie::create(['name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'ddi' => '992']);
$countrie_tz = Countrie::create(['name' => 'Tanzania, United Republic of', 'iso2' => 'TZ', 'iso3' => 'TZA', 'ddi' => '255']);
$countrie_th = Countrie::create(['name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'ddi' => '66']);
$countrie_tl = Countrie::create(['name' => 'Timor-Leste', 'iso2' => 'TL', 'iso3' => 'TLS', 'ddi' => '670']);
$countrie_tg = Countrie::create(['name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'ddi' => '228']);
$countrie_tk = Countrie::create(['name' => 'Tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'ddi' => '690']);
$countrie_to = Countrie::create(['name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'ddi' => '676']);
$countrie_tt = Countrie::create(['name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'ddi' => '1 868']);
$countrie_tn = Countrie::create(['name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'ddi' => '216']);
$countrie_tr = Countrie::create(['name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'ddi' => '90']);
$countrie_tm = Countrie::create(['name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'ddi' => '993']);
$countrie_tc = Countrie::create(['name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'ddi' => '1 649']);
$countrie_tv = Countrie::create(['name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'ddi' => '688']);
$countrie_ug = Countrie::create(['name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'ddi' => '256']);
$countrie_ua = Countrie::create(['name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'ddi' => '380']);
$countrie_ae = Countrie::create(['name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'ddi' => '971']);
$countrie_gb = Countrie::create(['name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'ddi' => '44']);
$countrie_um = Countrie::create(['name' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'ddi' => '1 808']);
$countrie_us = Countrie::create(['name' => 'United States', 'iso2' => 'US', 'iso3' => 'USA', 'ddi' => '1']);
$countrie_uy = Countrie::create(['name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'ddi' => '598']);
$countrie_uz = Countrie::create(['name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'ddi' => '998']);
$countrie_vu = Countrie::create(['name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'ddi' => '678']);
$countrie_ve = Countrie::create(['name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'ddi' => '58']);
$countrie_vn = Countrie::create(['name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'ddi' => '84']);
$countrie_vg = Countrie::create(['name' => 'Virgin Islands, British', 'iso2' => 'VG', 'iso3' => 'VGB', 'ddi' => '1 284']);
$countrie_vi = Countrie::create(['name' => 'Virgin Islands, U.S.', 'iso2' => 'VI', 'iso3' => 'VIR', 'ddi' => '1 340']);
$countrie_wf = Countrie::create(['name' => 'Wallis and Futuna', 'iso2' => 'WF', 'iso3' => 'WLF', 'ddi' => '681']);
$countrie_eh = Countrie::create(['name' => 'Western Sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'ddi' => '212 28']);
$countrie_ye = Countrie::create(['name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'ddi' => '967']);
$countrie_zm = Countrie::create(['name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'ddi' => '260']);
$countrie_zw = Countrie::create(['name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'ddi' => '263']);

/**
 * Criando o Relacionamento entre Continentes e Países por orden dos Países
 */
$countrie_af->addContinent($continents_as);        $countrie_ax->addContinent($continents_eu);        $countrie_al->addContinent($continents_eu);
$countrie_dz->addContinent($continents_af);        $countrie_as->addContinent($continents_oc);        $countrie_ad->addContinent($continents_eu);
$countrie_ao->addContinent($continents_af);        $countrie_ai->addContinent($continents_na);        $countrie_aq->addContinent($continents_an);
$countrie_ag->addContinent($continents_na);        $countrie_ar->addContinent($continents_sa);        $countrie_am->addContinent($continents_as);
$countrie_aw->addContinent($continents_na);        $countrie_au->addContinent($continents_oc);        $countrie_at->addContinent($continents_eu);
$countrie_az->addContinent($continents_as);        $countrie_bs->addContinent($continents_na);        $countrie_bh->addContinent($continents_as);
$countrie_bd->addContinent($continents_as);        $countrie_bb->addContinent($continents_na);        $countrie_by->addContinent($continents_eu);
$countrie_be->addContinent($continents_eu);        $countrie_bz->addContinent($continents_na);        $countrie_bj->addContinent($continents_af);
$countrie_bm->addContinent($continents_na);        $countrie_bt->addContinent($continents_as);        $countrie_bo->addContinent($continents_sa);
$countrie_bq->addContinent($continents_na);        $countrie_ba->addContinent($continents_eu);        $countrie_bw->addContinent($continents_af);
$countrie_bv->addContinent($continents_an);        $countrie_br->addContinent($continents_sa);        $countrie_io->addContinent($continents_as);
$countrie_bn->addContinent($continents_as);        $countrie_bg->addContinent($continents_eu);        $countrie_bf->addContinent($continents_af);
$countrie_bi->addContinent($continents_af);        $countrie_kh->addContinent($continents_as);        $countrie_cm->addContinent($continents_af);
$countrie_ca->addContinent($continents_na);        $countrie_cv->addContinent($continents_af);        $countrie_ky->addContinent($continents_na);
$countrie_cf->addContinent($continents_af);        $countrie_td->addContinent($continents_af);        $countrie_cl->addContinent($continents_sa);
$countrie_cn->addContinent($continents_as);        $countrie_cx->addContinent($continents_as);        $countrie_cc->addContinent($continents_as);
$countrie_co->addContinent($continents_sa);        $countrie_km->addContinent($continents_af);        $countrie_cd->addContinent($continents_af);
$countrie_cg->addContinent($continents_af);        $countrie_ck->addContinent($continents_oc);        $countrie_cr->addContinent($continents_na);
$countrie_ci->addContinent($continents_af);        $countrie_hr->addContinent($continents_eu);        $countrie_cu->addContinent($continents_na);
$countrie_cw->addContinent($continents_na);        $countrie_cy->addContinent($continents_as);        $countrie_cz->addContinent($continents_eu);
$countrie_dk->addContinent($continents_eu);        $countrie_dj->addContinent($continents_af);        $countrie_dm->addContinent($continents_na);
$countrie_do->addContinent($continents_na);        $countrie_ec->addContinent($continents_sa);        $countrie_eg->addContinent($continents_af);
$countrie_sv->addContinent($continents_na);        $countrie_gq->addContinent($continents_af);        $countrie_er->addContinent($continents_af);
$countrie_ee->addContinent($continents_eu);        $countrie_et->addContinent($continents_af);        $countrie_fk->addContinent($continents_sa);
$countrie_fo->addContinent($continents_eu);        $countrie_fj->addContinent($continents_oc);        $countrie_fi->addContinent($continents_eu);
$countrie_fr->addContinent($continents_eu);        $countrie_gf->addContinent($continents_sa);        $countrie_pf->addContinent($continents_oc);
$countrie_tf->addContinent($continents_an);        $countrie_ga->addContinent($continents_af);        $countrie_gm->addContinent($continents_af);
$countrie_ge->addContinent($continents_as);        $countrie_de->addContinent($continents_eu);        $countrie_gh->addContinent($continents_af);
$countrie_gi->addContinent($continents_eu);        $countrie_gr->addContinent($continents_eu);        $countrie_gl->addContinent($continents_na);
$countrie_gd->addContinent($continents_na);        $countrie_gp->addContinent($continents_na);        $countrie_gu->addContinent($continents_oc);
$countrie_gt->addContinent($continents_na);        $countrie_gg->addContinent($continents_eu);        $countrie_gw->addContinent($continents_af);
$countrie_gn->addContinent($continents_af);        $countrie_gy->addContinent($continents_sa);        $countrie_ht->addContinent($continents_na);
$countrie_hm->addContinent($continents_an);        $countrie_va->addContinent($continents_eu);        $countrie_hn->addContinent($continents_na);
$countrie_hk->addContinent($continents_as);        $countrie_hu->addContinent($continents_eu);        $countrie_is->addContinent($continents_eu);
$countrie_in->addContinent($continents_as);        $countrie_id->addContinent($continents_as);        $countrie_ir->addContinent($continents_as);
$countrie_iq->addContinent($continents_as);        $countrie_ie->addContinent($continents_eu);        $countrie_im->addContinent($continents_eu);
$countrie_il->addContinent($continents_as);        $countrie_it->addContinent($continents_eu);        $countrie_jm->addContinent($continents_na);
$countrie_jp->addContinent($continents_as);        $countrie_je->addContinent($continents_eu);        $countrie_jo->addContinent($continents_as);
$countrie_kz->addContinent($continents_as);        $countrie_ke->addContinent($continents_af);        $countrie_ki->addContinent($continents_oc);
$countrie_kp->addContinent($continents_as);        $countrie_kr->addContinent($continents_as);        $countrie_kw->addContinent($continents_as);
$countrie_kg->addContinent($continents_as);        $countrie_la->addContinent($continents_as);        $countrie_lv->addContinent($continents_eu);
$countrie_lb->addContinent($continents_as);        $countrie_ls->addContinent($continents_af);        $countrie_lr->addContinent($continents_af);
$countrie_ly->addContinent($continents_af);        $countrie_li->addContinent($continents_eu);        $countrie_lt->addContinent($continents_eu);
$countrie_lu->addContinent($continents_eu);        $countrie_mo->addContinent($continents_as);        $countrie_mk->addContinent($continents_eu);
$countrie_mg->addContinent($continents_af);        $countrie_mw->addContinent($continents_af);        $countrie_my->addContinent($continents_as);
$countrie_mv->addContinent($continents_as);        $countrie_ml->addContinent($continents_af);        $countrie_mt->addContinent($continents_eu);
$countrie_mh->addContinent($continents_oc);        $countrie_mq->addContinent($continents_na);        $countrie_mr->addContinent($continents_af);
$countrie_mu->addContinent($continents_af);        $countrie_yt->addContinent($continents_af);        $countrie_mx->addContinent($continents_na);
$countrie_fm->addContinent($continents_oc);        $countrie_md->addContinent($continents_eu);        $countrie_mc->addContinent($continents_eu);
$countrie_mn->addContinent($continents_as);        $countrie_me->addContinent($continents_eu);        $countrie_ms->addContinent($continents_na);
$countrie_ma->addContinent($continents_af);        $countrie_mz->addContinent($continents_af);        $countrie_mm->addContinent($continents_as);
$countrie_na->addContinent($continents_af);        $countrie_nr->addContinent($continents_oc);        $countrie_np->addContinent($continents_as);
$countrie_nl->addContinent($continents_eu);        $countrie_nc->addContinent($continents_oc);        $countrie_nz->addContinent($continents_oc);
$countrie_ni->addContinent($continents_na);        $countrie_ng->addContinent($continents_af);        $countrie_ne->addContinent($continents_af);
$countrie_nu->addContinent($continents_oc);        $countrie_nf->addContinent($continents_oc);        $countrie_mp->addContinent($continents_oc);
$countrie_no->addContinent($continents_eu);        $countrie_om->addContinent($continents_as);        $countrie_pk->addContinent($continents_as);
$countrie_pw->addContinent($continents_oc);        $countrie_ps->addContinent($continents_as);        $countrie_pa->addContinent($continents_na);
$countrie_pg->addContinent($continents_oc);        $countrie_py->addContinent($continents_sa);        $countrie_pe->addContinent($continents_sa);
$countrie_ph->addContinent($continents_as);        $countrie_pn->addContinent($continents_oc);        $countrie_pl->addContinent($continents_eu);
$countrie_pt->addContinent($continents_eu);        $countrie_pr->addContinent($continents_na);        $countrie_qa->addContinent($continents_as);
$countrie_re->addContinent($continents_af);        $countrie_ro->addContinent($continents_eu);        $countrie_ru->addContinent($continents_eu);
$countrie_rw->addContinent($continents_af);        $countrie_bl->addContinent($continents_na);        $countrie_sh->addContinent($continents_af);
$countrie_kn->addContinent($continents_na);        $countrie_lc->addContinent($continents_na);        $countrie_mf->addContinent($continents_na);
$countrie_pm->addContinent($continents_na);        $countrie_vc->addContinent($continents_na);        $countrie_ws->addContinent($continents_oc);
$countrie_sm->addContinent($continents_eu);        $countrie_st->addContinent($continents_af);        $countrie_sa->addContinent($continents_as);
$countrie_sn->addContinent($continents_af);        $countrie_rs->addContinent($continents_eu);        $countrie_sc->addContinent($continents_af);
$countrie_sl->addContinent($continents_af);        $countrie_sg->addContinent($continents_as);        $countrie_sx->addContinent($continents_na);
$countrie_sk->addContinent($continents_eu);        $countrie_si->addContinent($continents_eu);        $countrie_sb->addContinent($continents_oc);
$countrie_so->addContinent($continents_af);        $countrie_za->addContinent($continents_af);        $countrie_gs->addContinent($continents_an);
$countrie_ss->addContinent($continents_af);        $countrie_es->addContinent($continents_eu);        $countrie_lk->addContinent($continents_as);
$countrie_sd->addContinent($continents_af);        $countrie_sr->addContinent($continents_sa);        $countrie_sj->addContinent($continents_eu);
$countrie_sz->addContinent($continents_af);        $countrie_se->addContinent($continents_eu);        $countrie_ch->addContinent($continents_eu);
$countrie_sy->addContinent($continents_as);        $countrie_tw->addContinent($continents_as);        $countrie_tj->addContinent($continents_as);
$countrie_tz->addContinent($continents_af);        $countrie_th->addContinent($continents_as);        $countrie_tl->addContinent($continents_as);
$countrie_tg->addContinent($continents_af);        $countrie_tk->addContinent($continents_oc);        $countrie_to->addContinent($continents_oc);
$countrie_tt->addContinent($continents_na);        $countrie_tn->addContinent($continents_af);        $countrie_tr->addContinent($continents_eu);
$countrie_tm->addContinent($continents_as);        $countrie_tc->addContinent($continents_na);        $countrie_tv->addContinent($continents_oc);
$countrie_ug->addContinent($continents_af);        $countrie_ua->addContinent($continents_eu);        $countrie_ae->addContinent($continents_as);
$countrie_gb->addContinent($continents_eu);        $countrie_um->addContinent($continents_oc);        $countrie_us->addContinent($continents_na);
$countrie_uy->addContinent($continents_sa);        $countrie_uz->addContinent($continents_as);        $countrie_vu->addContinent($continents_oc);
$countrie_ve->addContinent($continents_sa);        $countrie_vn->addContinent($continents_as);        $countrie_vg->addContinent($continents_na);
$countrie_vi->addContinent($continents_na);        $countrie_wf->addContinent($continents_oc);        $countrie_eh->addContinent($continents_af);
$countrie_ye->addContinent($continents_as);        $countrie_zm->addContinent($continents_af);        $countrie_zw->addContinent($continents_af);

/*Estados do País Brasil*/
//pegando o id do País Brasil
//$countrie_br = Countrie::where('name','Brazil')->get()[0]->id;
$countrie_br = Countrie::where('id',32)->get()[0]->id;
State::create(['id' => 1, 'name' => 'Acre', 'initials' => 'AC', 'countrie_id' => $countrie_br]);
State::create(['id' => 2, 'name' => 'Alagoas', 'initials' => 'AL', 'countrie_id' => $countrie_br]);
State::create(['id' => 3, 'name' => 'Amazonas', 'initials' => 'AM', 'countrie_id' => $countrie_br]);
State::create(['id' => 4, 'name' => 'Amapá', 'initials' => 'AP', 'countrie_id' => $countrie_br]);
State::create(['id' => 5, 'name' => 'Bahia', 'initials' => 'BA', 'countrie_id' => $countrie_br]);
State::create(['id' => 6, 'name' => 'Ceará', 'initials' => 'CE', 'countrie_id' => $countrie_br]);
State::create(['id' => 7, 'name' => 'Distrito Federal', 'initials' => 'DF', 'countrie_id' => $countrie_br]);
State::create(['id' => 8, 'name' => 'Espírito Santo', 'initials' => 'ES', 'countrie_id' => $countrie_br]);
State::create(['id' => 9, 'name' => 'Goiás', 'initials' => 'GO', 'countrie_id' => $countrie_br]);
State::create(['id' => 10, 'name' => 'Maranhão', 'initials' => 'MA', 'countrie_id' => $countrie_br]);
State::create(['id' => 11, 'name' => 'Minas Gerais', 'initials' => 'MG', 'countrie_id' => $countrie_br]);
State::create(['id' => 12, 'name' => 'Mato Grosso do Sul', 'initials' => 'MS', 'countrie_id' => $countrie_br]);
State::create(['id' => 13, 'name' => 'Mato Grosso', 'initials' => 'MT', 'countrie_id' => $countrie_br]);
State::create(['id' => 14, 'name' => 'Pará', 'initials' => 'PA', 'countrie_id' => $countrie_br]);
State::create(['id' => 15, 'name' => 'Paraíba', 'initials' => 'PB', 'countrie_id' => $countrie_br]);
State::create(['id' => 16, 'name' => 'Pernambuco', 'initials' => 'PE', 'countrie_id' => $countrie_br]);
State::create(['id' => 17, 'name' => 'Piauí', 'initials' => 'PI', 'countrie_id' => $countrie_br]);
State::create(['id' => 18, 'name' => 'Paraná', 'initials' => 'PR', 'countrie_id' => $countrie_br]);
State::create(['id' => 19, 'name' => 'Rio de Janeiro', 'initials' => 'RJ', 'countrie_id' => $countrie_br]);
State::create(['id' => 20, 'name' => 'Rio Grande do Norte', 'initials' => 'RN', 'countrie_id' => $countrie_br]);
State::create(['id' => 21, 'name' => 'Rondônia', 'initials' => 'RO', 'countrie_id' => $countrie_br]);
State::create(['id' => 22, 'name' => 'Roraima', 'initials' => 'RR', 'countrie_id' => $countrie_br]);
State::create(['id' => 23, 'name' => 'Rio Grande do Sul', 'initials' => 'RS', 'countrie_id' => $countrie_br]);
$santaCatarina = State::create(['id' => 24, 'name' => 'Santa Catarina', 'initials' => 'SC', 'countrie_id' => $countrie_br]);
State::create(['id' => 25, 'name' => 'Sergipe', 'initials' => 'SE', 'countrie_id' => $countrie_br]);
State::create(['id' => 26, 'name' => 'São Paulo', 'initials' => 'SP', 'countrie_id' => $countrie_br]);
State::create(['id' => 27, 'name' => 'Tocantins', 'initials' => 'TO', 'countrie_id' => $countrie_br]);

/*Cidades*/
$cidadeGaropaba = City::create(['name'=>'Garopaba','state_id'=>$santaCatarina->id]);
$cidadeImbituba = City::create(['name'=>'Imbituba','state_id'=>$santaCatarina->id]);
$cidadeFlorianopolis = City::create(['name'=>'Florianópolis','state_id'=>$santaCatarina->id]);

/*Bairros de Florianopólis*/
$bairroIngles = Neighboarhood::create(['name'=>'Ingleses', 'city_id'=>$cidadeFlorianopolis->id]);
$bairroSantinho = Neighboarhood::create(['name'=>'Santinho', 'city_id'=>$cidadeFlorianopolis->id]);
$bairroPraiaBrava = Neighboarhood::create(['name'=>'Praia Brava', 'city_id'=>$cidadeFlorianopolis->id]);
$bairroCanasvieiras = Neighboarhood::create(['name'=>'Canasvieiras', 'city_id'=>$cidadeFlorianopolis->id]);

/*Bairros de Garopaba*/
$bairroCampoDuna = Neighboarhood::create(['name'=>'Campo Duna', 'city_id'=>$cidadeGaropaba->id]);
$bairroCentro = Neighboarhood::create(['name'=>'Centro', 'city_id'=>$cidadeGaropaba->id]);
$bairroLimpa = Neighboarhood::create(['name'=>'Limpa', 'city_id'=>$cidadeGaropaba->id]);
$bairroRessacada = Neighboarhood::create(['name'=>'Ressacada', 'city_id'=>$cidadeGaropaba->id]);

/*Logradouros do Bairro Campo Duna*/
$estradaGRP396 = Street::create(['name'=>'Estrada GRP-396','zip_code'=>'88945-000','neighboarhood_id'=>$bairroCampoDuna->id]);

/*tipo de endereço*/
$resedencial = AddressType::create(['name'=>'Residencial']);
$comercial = AddressType::create(['name'=>'Comercial']);
$cobranca = AddressType::create(['name'=>'Cobrança']);

/*endereços*/
//Address::create(['number'=>'255', 'address_type_id'=>$comercial, 'street_id'=>$estradaGRP396, 'person_physical_id'=>1]);