<?php
/**
 * Created by PhpStorm.
 * User: paulo
 * Date: 06/03/18
 * Time: 16:55
 */

namespace App\Http\Controllers\SoftEmp\Panel\Core\Configuration\Company;

use App\Http\Controllers\SoftEmp\Panel\CrudController;
use App\Http\Requests\Configuration\Company\CompanyDataRequest;
use App\Models\Core\Company\Company;
use Illuminate\Http\Request;

class CompanyController extends CrudController
{
    protected $pathView = 'softemp.panel.core.configuration.company';
    protected $groupRoute = 'panel.configuration.company';

    public function __construct(Company $model,Request $request)
    {
        parent::__construct($model, $request,$this->groupRoute, $this->pathView);
    }

//    public function index()
//    {
//        $model = $this->model->getCompanySoftwareOwner();
////        $r = $model->whereHas('person.address', function ($query){
////            //dd($query->with('person.address')->where('address_type_id','1'));
////            return $query->with('person.address')->where('address_type_id','1');
////            //dd($query->number);
////        });
//
//        $model->with('person.address');
////        dd($r->first());
////        $model->with('person.address');
//        //dd($model-);
//        //$data = $model->first();
//        //$this->arrayData['data'] = $data;
//
//        $address = $model->first()->person->address->first();
//        dd($address->addressStreets->neighboarhoods->first(['name','id']));
//        dd($address->addressStreets->neighboarhoods->pluck('name','id'));
//        //$address = $data->person->address->where('address_type_id',1)->first();
//
//        //dd($address->addressStreets->neighboarhoods->name);
//        //$this->arrayData['address'] = $address;
//        return view("$this->pathView.index", $this->arrayData);
//    }

    public function index()
    {
        $model = $this->model->getCompanySoftwareOwner();

        $data = $model->first();

        $this->arrayData['data'] = $data;

        $address = $data->person->address->where('address_type_id',1)->first();

//        dd($address->addressStreets->neighboarhoods->name);
        $this->arrayData['address'] = $address;
//        dd($address);

        return view("$this->pathView.index", $this->arrayData);
    }

    public function updateData($id, CompanyDataRequest $request)
    {
        $company = Company::find($id);

        $result = $company->update($request->all());
        if ($result) {
            return redirect()->route("{$this->groupRoute}.index")->with('success',
                trans('panel/crud.msg_updated_sucess'));
        }

        return redirect()
            ->route("{$this->groupRoute}.index", ['id' => $id])
            ->withErrors(['errors' => trans('panel/crud.msg_updated_error')])
            ->withInput();
        //return parent::update($id); // TODO: Change the autogenerated stub
    }
//    public function index()
//    {
//        $data = $this->model->getCompanySoftwareOwner();
//
//        dd($data->with('person','person.address')->get());
//
//        return view("{$this->pathView}.index", compact('data'));
//    }


}
