<?php

namespace App\Http\Controllers\SoftEmp\Panel\Base\AccessControl;

use App\Http\Controllers\SoftEmp\Panel\CrudController;
use App\Models\Base\AccessControl\Role;
use Illuminate\Http\Request;

class RoleController extends CrudController
{
    /**
     * RoleController constructor.
     * @param Role $role
     */
    public function __construct()
    {
        $this->model = new Role;
        //$this->request = $request;
        $this->pathView = 'softemp.panel.base.access_control.role';
        $this->groupRoute = 'panel.access.control.role';
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request['slug'] = $request->name;

        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
