<?php

namespace App\Http\Controllers\SoftEmp\Provedor;

use App\Models\Provedor\MkBlock;
use Illuminate\Http\Request;

class MkBlockController extends CrudController
{
    private $pathImg = 'storage/softemp/panel/uploads/sobre/';

    protected $pathView = 'softemp.provedor.mkblock';
    protected $groupRoute = 'softemp.provedor.mkblock';

    public function __construct(MkBlock $model, Request $request)
    {
        parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    public function index()
    {

       //$about = $this->model->personLegals->find(env('EMPRESA_SOFTWARE_ID'));
        //$about = $this->model->wherePersonLegalId(env('EMPRESA_SOFTWARE_ID'))->first();
        $this->arrayData['about'] = $this->model->firstOrFail();


        return parent::index(); // TODO: Change the autogenerated stub
        //return view("{$this->pathView}.index",compact('about','pathImg'));
    }
}
