<?php

namespace App\Http\Controllers\SoftEmp\Panel\Provedor;

use App\Http\Controllers\Controller;
use App\Models\Provedor\MkAuth\Client;
use Illuminate\Http\Request;

class ProvedorController extends Controller
{
    protected $pathView = 'softemp.panel.provedor';
    protected $groupRoute = 'softemp.panel.provedor';

    private $client;
    private $arrayData = [];

    /**
     * ProvedorController constructor.
     * @param Request $request
     * @param Client $client
     */
    public function __construct(Request $request, Client $client)
    {
        $this->client = $client;
        //parent::__construct($model, $request, $this->groupRoute, $this->pathView);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {

        $this->arrayData['countClientActive'] = $this->client->countActive();
        $this->arrayData['countClientBlocked'] = $this->client->countBlocked();

        return view("$this->pathView.index", $this->arrayData);
        //return parent::index(); // TODO: Change the autogenerated stub
    }

}
